```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(xtable)
library(plyr)
library(gridExtra)
setwd("~/Code/RunR/")
source("gpsStats.R")
source("gpsPlot.R")
source("runR.R")
setwd("~/Code/RunR/data")
updateLocalStore(maxDownloads=11)
nrec = 3
```

<style type="text/css">
body{
  width: 70%;
  margin-left: auto;
  margin-right: auto;
}
body, td {
   font-size: 14px;
   font-weight: 200;
   font-family: "Helvetica Neue", Helvetica;
}
td{
  padding-right: 10px;
}
h1, h2{
  font-weight: lighter;
}
</style>

<link href='http://fonts.googleapis.com/css?family=Raleway:400,200' rel='stylesheet' type='text/css'>


Analysis of Nike+ running data with RunR
========================================================
-----
RunR downloads your running data using the Nike+ API, calculates some basic statistics, and visualises the result. Source code available on [Github](https://github.com/synergenz/RunR).

Last `r nrec` runs
--------------------------------------------------------
-----
```{r fig.width=11, fig.height=10, echo=FALSE, fig.align='center', cache=FALSE}
par(mfrow=c(nrec, 1))
ordered = stats[order(stats$startTime),]
n = nrow(stats)
for(i in 1:nrec){
  id = ordered$activityId[n-i]
  plotSpeedElevation(gps[gps$activityId == id,], time=F, pace=F, legend=F, date=ordered$startTime[n-i])
}
```

Map of last (and all) runs
--------------------------------------------------------
-----
```{r echo=FALSE, comment="", results='asis', fig.width=11, fig.height=5, warning=FALSE}
id = ordered$activityId[n]
par(mfrow=c(1,2))
p1 = plotMap(gps[gps$activityId == id,], zoomFac=14, src="stamen", type="toner", col="red")
p2 = plotMap(gps, zoomFac=13, src="stamen", type="toner", col="red")
grid.arrange(p1, p2, ncol=2)
```

Graphical summary of last 31 days
--------------------------------------------------------
-----
```{r echo=FALSE, comment="", results='asis', fig.width=15, fig.height=4}
filterby = "recent"
if(filterby == "month"){
  year = 2013
  month = 3
  statsFiltered = filterByMonth(stats, year, month)
} else if (filterby == "recent"){
  days = 31
  statsFiltered = filterByRecent(stats, days)
}
par(mfrow=c(1,3))
plotDistanceBars(statsFiltered)
plotDistanceBarsCal(statsFiltered)
plotPaceDistance(statsFiltered)
```

Graphical summary all runs
--------------------------------------------------------
```{r echo=FALSE, comment="", results='asis', fig.width=15, fig.height=4}
par(mfrow=c(1,3))
plotDistanceBars(stats)
plotDistanceBarsCal(stats)
plotPaceDistance(stats)
```

Summary of all runs
--------------------------------------------------------
-----
```{r echo=FALSE, comment="", results='asis'}
mrs = multiRunSummary(stats)
df = ldply(mrs, data.frame)
print(xtable(df, align="ll|llr"), type="html", include.rownames=F, include.colnames=F, html.table.attributes=c(border=2))
```

Summary of last 31 days
--------------------------------------------------------
```{r echo=FALSE, comment="", results='asis'}
mrs = multiRunSummary(statsFiltered)
df = ldply(mrs, data.frame)
print(xtable(df, align="ll|llr"), type="html", include.rownames=F, include.colnames=F, html.table.attributes=c(border=2))
```
    

